os:
- linux

sudo: required
dist: trusty

languages: java

cache:
- apt

before_install:
- sudo apt-get -qq update -y
- sudo apt-get install r-base -y

script:
- ./gradlew dist
- cd tests
- bash ./run.sh

notifications:
  email:
    on_success: always
    on_failure: always
